Colorscheme
Jonathanlouiskirk/reVENUE pull request #104
Opened 2022-07-06 20:55 UTC by Jonathanlouiskirk

this changes the design to black and red color scheme and also displays if there is a review for each venue on the home page or not.

2022-07-06 22:36 UTC, jonfaustothen submitted a review, later dismissed

2022-07-06 22:42 UTC, storrer requested changes

2022-07-06 22:42 UTC, storrer commented on revenue/revenueapp/templates/individual_venue.html
> +<h1 id="Individual_venue_heading_text">User review</h1>
Can you pluralize this as the site has been changed to use multiple reviews and multiple users? It currently shows up on the page even if there are no reviews, fyi. Changing it to 'User Reviews' could work as a header for an empty part of the page.

2022-07-06 22:43 UTC, storrer commented on revenue/revenueapp/templates/individual_venue.html
> +<h1 id="Individual_venue_heading_text">User review</h1>
![image](https://user-images.githubusercontent.com/13088830/177655271-0bfbf78c-bda4-4400-8f9f-d914dedbae72.png)
This is what I am talking about: there is no user review on this page and there **could** be many reviews.

2022-07-07 01:04 UTC, Jonathanlouiskirk commented on revenue/revenueapp/templates/individual_venue.html
> +<h1 id="Individual_venue_heading_text">User review</h1>
I fixed this with  following commit

2022-07-07 01:45 UTC, jonfaustothen approved these changes

2022-07-07 01:54 UTC, storrer approved these changes

2022-07-07 01:56 UTC, merged