updated about page, added comments on styles.css, and added link to h…
Jonathanlouiskirk/reVENUE pull request #38
Opened 2022-05-13 00:26 UTC by jonfaustothen

…ome.html

2022-05-13 06:08 UTC, storrer requested changes
The only thing I would ask you to change is your commit message. Right now the verbs are in the past tense and the first word is not capitalized. For example, your commit message ought to read: `Update about page, add comments on style.css, and add link to home.html`
I am getting these rules from videos in the Git modules on Canvas/Courseworks and online articles about Git commit message guidelines.
I am not only asking this so that our repository's commit history will show that we can write these short commit messages. If you do not want to use these guidelines let me know and I will approve your pull request as it is.

2022-05-13 18:42 UTC, Jonathanlouiskirk approved these changes

2022-05-15 20:53 UTC, jonfaustothen commented
makes sense Chris!  I edited the commit message and will write future messages in present tense

2022-05-15 22:13 UTC, storrer approved these changes

2022-05-15 22:14 UTC, merged