Jonkfeature/venue html
Jonathanlouiskirk/reVENUE pull request #49
Opened 2022-05-20 00:08 UTC by Jonathanlouiskirk

JONATHAN K:
created htmls for individual venue, venue review and create a venue. updated urls.py and views.py. I also started to add some css and forms to the htmls pages (work in progress)

2022-05-23 15:46 UTC, storrer requested changes
There are a number of problems with the files changed and added in this pull request. I apologize for not getting back to you earlier, but I have been travelling.

2022-05-24 22:55 UTC, storrer requested changes
In `revenueapp/urls.py` lines 12 and 13 have been deleted but we need them in order to load static files.  In `revenueapp/models.py` line 42 the `unique` constraint on the `venue` field has been changed to False. It should be True because we only want one Review per Venue right now. In revenue/urls.py you have changed the home page from `revenue/` to an empty string at line 21. Is this intentional?

2022-05-25 00:55 UTC, storrer approved these changes, later dismissed
Everything looks good. Right now the code displays just the template `individual_venue.html` without passing any of the venue data to the template. The view `IndividualVenueView` needs to access the database to get the individual venue data and then pass it to the template via the context. Also, the URL pattern for individual venues needs be written to make our home page work as intended.

2022-05-26 22:34 UTC, jonfaustothen submitted a review, later dismissed

2022-05-27 18:58 UTC, closed without merging