displayed venue on home page even if no review, display all data in t…
Jonathanlouiskirk/reVENUE pull request #71
Opened 2022-05-31 02:14 UTC by Jonathanlouiskirk

…emplate

2022-05-31 16:16 UTC, jonfaustothen approved these changes, later dismissed

2022-05-31 22:40 UTC, storrer requested changes
Have you tested the home page? It looks, based on the code in `HomeView.get()` that the variable `venues` is assigned twice: once on line 16 and again on line 21.

2022-06-01 00:06 UTC, storrer approved these changes

2022-06-01 00:15 UTC, jonfaustothen approved these changes

2022-06-01 00:17 UTC, merged