Combined all css to one file and modified css on all html pages
Jonathanlouiskirk/reVENUE pull request #92
Opened 2022-06-20 04:49 UTC by Jonathanlouiskirk

I still need to do a little cleaning up in the styles.css file. Some stuff in there we don't need.

2022-06-20 06:51 UTC, storrer requested changes
The `individual_venue.html` template has <div> elements that don't have a closing </div>. There are multiple <div> elements with `id="bar_text"`. You "shouldn't" have more than one element with the same id in an HTML document. [Here is a post about why id's should be unique](https://stackoverflow.com/a/44009054) .

2022-06-20 07:04 UTC, storrer commented on revenue/revenueapp/templates/revenueapp/venue_form.html
> +    <form id="Review_form">
The `method` attribute is necessary for the form to work. Please add it back to this form element, as well.

2022-06-20 07:18 UTC, storrer commented
I kinda like the grey background more...

2022-06-22 22:43 UTC, jonfaustothen approved these changes

2022-06-23 02:42 UTC, storrer approved these changes

2022-06-23 12:15 UTC, merged