Added genres to fixture
Jonathanlouiskirk/reVENUE pull request #95
Opened 2022-06-23 23:55 UTC by jonfaustothen

Added more genres to fixture file, also changed background color with this push to slate blue

2022-06-24 00:00 UTC, Jonathanlouiskirk submitted a review, later dismissed

2022-06-24 00:41 UTC, storrer approved these changes, later dismissed

2022-06-25 00:09 UTC, Jonathanlouiskirk submitted a review, later dismissed

2022-06-25 21:32 UTC, Jonathanlouiskirk approved these changes, later dismissed

2022-06-28 02:57 UTC, storrer requested changes
Looks good, but the review_form.html navbar logout/login `<li>` has been changed back to `review_create` which no longer functions the way it used to.

2022-06-28 02:57 UTC, storrer commented on revenue/revenueapp/templates/revenueapp/review_form.html
> -      <li><a href="{% url 'logout' %}?next={% url 'individual_venue' venue.id %}">Logout</a></li>
Can you add this line back into the navbar for this page?

2022-06-28 02:58 UTC, storrer commented on revenue/revenueapp/templates/revenueapp/review_form.html
> +         <li><a href="{% url 'review_create' %}">Review</a></li>
This link no longer works and should be replaced.

2022-06-28 02:59 UTC, storrer commented on revenue/revenueapp/templates/revenueapp/review_form.html
> -    <a href="{% url 'individual_venue' venue.id %}">Cancel</a>
I also added a cancel button and the review's  name to the form, and it has been overwritten with an older version of this form.

2022-06-28 03:00 UTC, storrer approved these changes

2022-06-28 03:01 UTC, storrer requested changes
There are no merge conflicts to resolve so I'm un-approving this. You replaced all the changes I made to review_form.html...

2022-06-28 15:08 UTC, Jonathanlouiskirk approved these changes

2022-06-28 20:17 UTC, storrer approved these changes

2022-06-28 21:06 UTC, merged